services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
    - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
     - '9090:9090'
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
    - ./prometheus:/etc/prometheus
    - prometheus-data:/prometheus
  
  node_exporter_1:
    image: prom/node-exporter
    container_name: node_exporter_1
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
     - '9101:9100'

  node_exporter_2:
    image: prom/node-exporter
    container_name: node_exporter_2
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
    - '9102:9100'
    
  node_exporter_3:
    image: prom/node-exporter
    container_name: node_exporter_3
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
    - '9103:9100'



volumes:
  grafana-storage: {}  
  prometheus-data: {} 